version: "3"
services:
  web:
    image: httpd:2.4
    volumes:
      - ./public_html:/usr/local/apache2/htdocs
    ports:
      - "5000:80"

  go:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"

